version: "2"
services:
  albot-cpp:
    # Say where the work directory and docker file is for this service
    build:
      context: .
      dockerfile: Dockerfile
    # Base image
    image: ubuntu:20.10
    container_name: albot-cpp
    # Work directory inside image
    working_dir: /var/albot-cpp
    ports:
      - "5000:5000"
    # Connect files from outside the container as given files inside the container
    volumes:
      - ./.env:/var/albot-cpp/.env
      - ./bot.out.json:/var/albot-cpp/bot.out.json
      - ./bot.json:/var/albot-cpp/bot.json
