# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linuxlite/shared/albot-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linuxlite/shared/albot-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linuxlite/shared/albot-cpp/CMakeFiles /home/linuxlite/shared/albot-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linuxlite/shared/albot-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named albot-cpp

# Build rule for target.
albot-cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 albot-cpp
.PHONY : albot-cpp

# fast build rule for target.
albot-cpp/fast:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/build
.PHONY : albot-cpp/fast

HttpWrapper/HttpWrapper.o: HttpWrapper/HttpWrapper.cpp.o

.PHONY : HttpWrapper/HttpWrapper.o

# target to build an object file
HttpWrapper/HttpWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/HttpWrapper/HttpWrapper.cpp.o
.PHONY : HttpWrapper/HttpWrapper.cpp.o

HttpWrapper/HttpWrapper.i: HttpWrapper/HttpWrapper.cpp.i

.PHONY : HttpWrapper/HttpWrapper.i

# target to preprocess a source file
HttpWrapper/HttpWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/HttpWrapper/HttpWrapper.cpp.i
.PHONY : HttpWrapper/HttpWrapper.cpp.i

HttpWrapper/HttpWrapper.s: HttpWrapper/HttpWrapper.cpp.s

.PHONY : HttpWrapper/HttpWrapper.s

# target to generate assembly for a file
HttpWrapper/HttpWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/HttpWrapper/HttpWrapper.cpp.s
.PHONY : HttpWrapper/HttpWrapper.cpp.s

albot-cpp.o: albot-cpp.cpp.o

.PHONY : albot-cpp.o

# target to build an object file
albot-cpp.cpp.o:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/albot-cpp.cpp.o
.PHONY : albot-cpp.cpp.o

albot-cpp.i: albot-cpp.cpp.i

.PHONY : albot-cpp.i

# target to preprocess a source file
albot-cpp.cpp.i:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/albot-cpp.cpp.i
.PHONY : albot-cpp.cpp.i

albot-cpp.s: albot-cpp.cpp.s

.PHONY : albot-cpp.s

# target to generate assembly for a file
albot-cpp.cpp.s:
	$(MAKE) -f CMakeFiles/albot-cpp.dir/build.make CMakeFiles/albot-cpp.dir/albot-cpp.cpp.s
.PHONY : albot-cpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... albot-cpp"
	@echo "... HttpWrapper/HttpWrapper.o"
	@echo "... HttpWrapper/HttpWrapper.i"
	@echo "... HttpWrapper/HttpWrapper.s"
	@echo "... albot-cpp.o"
	@echo "... albot-cpp.i"
	@echo "... albot-cpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

